// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the bound service exposing text-to-speech synthesis, voice
 * recording, and file/folder pickers to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildPodcast turns a "Speaker: line" script into one stitched episode,
 * giving each speaker their own saved voice (voices maps a speaker name,
 * as it appears in the script, to a speakerFile path — same kind of path
 * PickSpeakerFile/ConfirmRecording return). Unrecognized or unmapped
 * speaker names fall back to the model's default voice. A trailing
 * "[emotion]" tag on a turn (e.g. "Host: line [excited]") is parsed off by
 * tts.ParseScript and sent as that turn's instruct — see the same caveats
 * as Synthesize's instruct param (requires a patched llama-tts build,
 * effect on the Base checkpoint unverified). Shares the same
 * sequential one-model-at-a-time pipeline and progress/stop plumbing as
 * Synthesize (see runSequentialJobs, beginJob) — events are emitted on
 * "podcast:progress"/"podcast:chunk" instead, so a Podcast tab's
 * listeners don't collide with a Compose tab's.
 */
export function BuildPodcast(script: string, voices: { [_ in string]?: string } | null, lang: string, outputDir: string): $CancellablePromise<$models.SynthesizeResult | null> {
    return $Call.ByID(1374234153, script, voices, lang, outputDir);
}

/**
 * Configure (re)initializes the TTS engine with explicit paths, for when
 * env vars aren't set and the user picks paths from the UI instead.
 */
export function Configure(binPath: string, modelPath: string, mmprojPath: string): $CancellablePromise<void> {
    return $Call.ByID(3027973171, binPath, modelPath, mmprojPath);
}

/**
 * ConfirmRecording "perfects" the last stopped recording — trims
 * leading/trailing silence and normalizes volume — and saves it to a
 * stable per-user location so it can be reused as a cloning reference
 * across requests and future launches, exactly like a file picked via
 * PickSpeakerFile.
 */
export function ConfirmRecording(): $CancellablePromise<string> {
    return $Call.ByID(1386945410);
}

/**
 * DiscardRecording throws away the last stopped recording (the user hit
 * "record again" or cancelled).
 */
export function DiscardRecording(): $CancellablePromise<void> {
    return $Call.ByID(888139760);
}

/**
 * PickOutputFolder opens a native folder picker for where generated
 * audio should be saved, returning the chosen path (empty if cancelled).
 */
export function PickOutputFolder(): $CancellablePromise<string> {
    return $Call.ByID(1178122629);
}

/**
 * PickSpeakerFile opens a native file picker for a reference wav/mp3
 * clip to clone a voice from, returning the chosen path (empty if
 * cancelled).
 */
export function PickSpeakerFile(): $CancellablePromise<string> {
    return $Call.ByID(1931421583);
}

/**
 * SaveGeneratedAudio opens a native "Save As" dialog defaulting to
 * suggestedName and writes audioB64 (the wav bytes returned by Synthesize/
 * BuildPodcast) to the chosen path — for a result that was only played
 * back, not auto-saved via outputDir. defaultDir, when non-empty, is the
 * directory the dialog opens in (e.g. the sidebar's configured Output
 * folder), so a user who already picked one doesn't have to navigate back
 * to it every time. Returns the chosen path, or "" if the user cancelled
 * the dialog.
 */
export function SaveGeneratedAudio(audioB64: string, suggestedName: string, defaultDir: string): $CancellablePromise<string> {
    return $Call.ByID(3138381877, audioB64, suggestedName, defaultDir);
}

/**
 * StartRecording begins capturing microphone audio via the system's
 * arecord for use as a voice-cloning reference. See internal/recorder
 * for why this happens natively instead of via the browser's
 * getUserMedia (which WebKitGTK disables by default on Linux).
 */
export function StartRecording(): $CancellablePromise<void> {
    return $Call.ByID(4179347122);
}

/**
 * StopRecording ends the in-progress recording and returns the raw
 * audio base64-encoded so the UI can preview it before committing.
 */
export function StopRecording(): $CancellablePromise<string> {
    return $Call.ByID(3372080196);
}

/**
 * StopSynthesis cancels an in-progress Synthesize or BuildPodcast call,
 * if any. The currently-running llama-tts process is killed
 * (exec.CommandContext ties its lifetime to the context); the sequential
 * job loop then sees the cancellation and stops before starting the next
 * piece. A no-op if nothing is running.
 */
export function StopSynthesis(): $CancellablePromise<void> {
    return $Call.ByID(2342647997);
}

/**
 * Synthesize converts text to speech, optionally cloning a voice from
 * speakerFile (a wav/mp3 reference clip). lang is a language code such as
 * "en", "zh", "ja" — empty uses the model default. instruct is an optional
 * natural-language style/emotion instruction (e.g. "speak with a hint of
 * panic") used as the default for any text with no inline "[emotion]" tag
 * of its own (see buildComposeJobs); empty omits it entirely for untagged
 * text. Requires a llama-tts build with --tts-instruct support (see
 * internal/tts.Engine's package doc) — on a stock build this will fail
 * the whole request rather than silently ignoring it. When outputDir is
 * non-empty, the generated wav is kept there permanently; otherwise it's
 * written to a scratch cache dir and removed once read. Progress is
 * reported via the "tts:progress" event while generation runs.
 */
export function Synthesize(text: string, lang: string, speakerFile: string, instruct: string, outputDir: string): $CancellablePromise<$models.SynthesizeResult | null> {
    return $Call.ByID(2841893221, text, lang, speakerFile, instruct, outputDir);
}
