// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProgressEvent is emitted on the "tts:progress" event as synthesis
 * runs. Percent is a rough heuristic (there's no true total — the model
 * decides generation length via its own end-of-speech token), capped
 * below 100 until the process actually finishes.
 */
export interface ProgressEvent {
    "percent": number;
}

/**
 * SynthesizeResult is returned to the frontend after synthesis. AudioB64
 * is the wav file base64-encoded so the webview can play it directly via
 * a data: URL without needing filesystem access. SavedPath is set only
 * when the caller supplied an outputDir — otherwise nothing is kept on
 * disk beyond the call.
 */
export interface SynthesizeResult {
    "audioB64": string;
    "savedPath"?: string;
}
